USE dikoin_manuales;

-- Taxonomia normalizada de productos DIKOIN basada en catalogo_productos_dikoin.xlsx
CREATE TABLE IF NOT EXISTS product_families (
  id BIGINT NOT NULL AUTO_INCREMENT,
  code VARCHAR(20) NOT NULL,
  name_es VARCHAR(160) NOT NULL,
  name_en VARCHAR(160) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_families_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_categories (
  id BIGINT NOT NULL AUTO_INCREMENT,
  code VARCHAR(20) NOT NULL,
  name_es VARCHAR(180) NOT NULL,
  name_en VARCHAR(180) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_categories_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE products ADD COLUMN IF NOT EXISTS name_es VARCHAR(160) NULL AFTER name;
ALTER TABLE products ADD COLUMN IF NOT EXISTS name_en VARCHAR(160) NULL AFTER name_es;
ALTER TABLE products ADD COLUMN IF NOT EXISTS family_code VARCHAR(20) NULL AFTER family;
ALTER TABLE products ADD COLUMN IF NOT EXISTS family_id BIGINT NULL AFTER family_code;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category_codes VARCHAR(120) NULL AFTER category;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description_es VARCHAR(600) NULL AFTER description;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description_en VARCHAR(600) NULL AFTER description_es;

CREATE TABLE IF NOT EXISTS product_category_assignments (
  product_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  PRIMARY KEY (product_id, category_id),
  CONSTRAINT fk_product_category_assignments_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_category_assignments_category FOREIGN KEY (category_id) REFERENCES product_categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO product_families (code, name_es, name_en) VALUES
  ('FL', 'Mecánica de fluidos', 'Fluid Mechanics'),
  ('FLB', 'Módulos para banco hidráulico', 'Hydraulic Bench Modules'),
  ('MH', 'Máquinas hidráulicas', 'Hydraulic Machines'),
  ('TH', 'Turbomáquinas hidráulicas', 'Hydraulic Turbomachines'),
  ('HD', 'Hidráulica e hidrología', 'Hydraulics and Hydrology'),
  ('TA', 'Tratamiento de aguas', 'Water Treatment'),
  ('EN', 'Energías renovables', 'Renewable Energy'),
  ('AC', 'Aire acondicionado / bomba de calor', 'Air Conditioning / Heat Pump'),
  ('IT', 'Intercambio térmico', 'Heat Exchange'),
  ('RF', 'Refrigeración', 'Refrigeration'),
  ('TC', 'Transferencia de calor', 'Heat Transfer'),
  ('TD', 'Termodinámica / motores', 'Thermodynamics / Engines'),
  ('IQ', 'Ingeniería química', 'Chemical Engineering'),
  ('ST', 'Estructuras', 'Structures'),
  ('STZ', 'STZ', 'STZ'),
  ('MM', 'Mantenimiento y montaje', 'Maintenance and Assembly')
ON DUPLICATE KEY UPDATE name_es = VALUES(name_es), name_en = VALUES(name_en);

INSERT INTO product_categories (code, name_es, name_en) VALUES
  ('A', 'Fundamentos de Mecánica de Fluidos', 'Fluid Mechanics Fundamentals'),
  ('C', 'Hidráulica, Hidrología y Tratamiento de aguas', 'Hydraulics, Hydrology and Water Treatment'),
  ('B', 'Máquinas y Turbomáquinas Hidráulicas', 'Hydraulic Machines and Turbomachines'),
  ('D', 'Aerodinámica', 'Aerodynamics'),
  ('I', 'Ingeniería Química', 'Chemical Engineering'),
  ('E', 'Energías Renovables', 'Renewable Energy'),
  ('F', 'Termodinámica', 'Thermodynamics'),
  ('K', 'Mecánica', 'Mechanics'),
  ('N', 'Mantenimiento', 'Maintenance')
ON DUPLICATE KEY UPDATE name_es = VALUES(name_es), name_en = VALUES(name_en);

INSERT INTO products (code, name, name_es, name_en, family, family_code, category, category_codes, description, description_es, description_en, active, created_at, updated_at) VALUES
  ('FL 01.1', 'Grupo Hidráulico', 'Grupo Hidráulico', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Unidad autónoma, portátil y económica de suministro de energía hidráulica para alimentar equipos didácticos de laboratorio.', 'Unidad autónoma, portátil y económica de suministro de energía hidráulica para alimentar equipos didácticos de laboratorio.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 01.2', 'Flujo sobre Vertederos', 'Flujo sobre Vertederos', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Set de cuatro placas de vertedero para estudiar la medida de caudal y el comportamiento de la lámina de agua en canal.', 'Set de cuatro placas de vertedero para estudiar la medida de caudal y el comportamiento de la lámina de agua en canal.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 01.3', 'Banco Hidrostático', 'Banco Hidrostático', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Banco para estudiar propiedades y fenómenos de la estática de fluidos, como densidad, presión, capilaridad, viscosidad y flotabilidad.', 'Banco para estudiar propiedades y fenómenos de la estática de fluidos, como densidad, presión, capilaridad, viscosidad y flotabilidad.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 01.4', 'Banco Hidráulico', 'Banco Hidráulico', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Banco hidráulico diseñado como mesa de trabajo para instalar equipos didácticos que necesitan aporte de caudal.', 'Banco hidráulico diseñado como mesa de trabajo para instalar equipos didácticos que necesitan aporte de caudal.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 01.6', 'Banco Hidráulico 250L', 'Banco Hidráulico 250L', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Banco hidráulico de 250 litros para alimentar equipos didácticos y medir caudales mediante depósitos volumétricos.', 'Banco hidráulico de 250 litros para alimentar equipos didácticos y medir caudales mediante depósitos volumétricos.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 01.7', 'Banco Hidráulico Gran Caudal', 'Banco Hidráulico Gran Caudal', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Banco hidráulico de gran caudal con dos bombas en paralelo para trabajar con equipos que requieren mayor suministro de agua.', 'Banco hidráulico de gran caudal con dos bombas en paralelo para trabajar con equipos que requieren mayor suministro de agua.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 02.1', 'Pérdidas DE Carga', 'Pérdidas DE Carga', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar pérdidas de carga por fricción en tuberías y pérdidas producidas por accesorios, válvulas y elementos de medida.', 'Equipo para estudiar pérdidas de carga por fricción en tuberías y pérdidas producidas por accesorios, válvulas y elementos de medida.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 04.1', 'Redes DE Tuberías', 'Redes DE Tuberías', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo flexible para estudiar y analizar el flujo a través de distintas configuraciones de redes de tuberías.', 'Equipo flexible para estudiar y analizar el flujo a través de distintas configuraciones de redes de tuberías.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 06.1', 'Efecto Venturi, Bernoulli Y Cavitación', 'Efecto Venturi, Bernoulli Y Cavitación', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar el efecto Venturi, el teorema de Bernoulli y la observación del fenómeno de cavitación.', 'Equipo para estudiar el efecto Venturi, el teorema de Bernoulli y la observación del fenómeno de cavitación.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 06.2', 'Bernoulli', 'Bernoulli', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo sencillo para estudiar en profundidad la ecuación de Bernoulli y leer presiones en un conducto mediante manómetro multitubo.', 'Equipo sencillo para estudiar en profundidad la ecuación de Bernoulli y leer presiones en un conducto mediante manómetro multitubo.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 06.3', 'Estudio DE LA Cavitación', 'Estudio DE LA Cavitación', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar y visualizar el fenómeno de cavitación bajo diferentes condiciones de presión y caudal.', 'Equipo para estudiar y visualizar el fenómeno de cavitación bajo diferentes condiciones de presión y caudal.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 09.2', 'Ariete Hidráulico', 'Ariete Hidráulico', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos | C - Hidráulica, Hidrología y Tratamiento de aguas', 'A, C', 'Equipo para estudiar el fenómeno de ariete hidráulico o golpe de ariete y analizar variaciones bruscas de presión en conducciones.', 'Equipo para estudiar el fenómeno de ariete hidráulico o golpe de ariete y analizar variaciones bruscas de presión en conducciones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 10.1', 'Presión sobre Superficies Sumergidas', 'Presión sobre Superficies Sumergidas', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para determinar la fuerza hidrostática ejercida sobre superficies sumergidas y estudiar el centro de presiones.', 'Equipo para determinar la fuerza hidrostática ejercida sobre superficies sumergidas y estudiar el centro de presiones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 10.2', 'Altura Metacéntrica', 'Altura Metacéntrica', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar la estabilidad de cuerpos flotantes y determinar la altura metacéntrica.', 'Equipo para estudiar la estabilidad de cuerpos flotantes y determinar la altura metacéntrica.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 11.1', 'Impacto sobre Álabes', 'Impacto sobre Álabes', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar la fuerza ejercida por un chorro de agua sobre distintos álabes o superficies de impacto.', 'Equipo para estudiar la fuerza ejercida por un chorro de agua sobre distintos álabes o superficies de impacto.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 12.1', 'Salida POR Orificios', 'Salida POR Orificios', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para analizar la salida de caudal por orificios, el coeficiente de descarga y la trayectoria del chorro.', 'Equipo para analizar la salida de caudal por orificios, el coeficiente de descarga y la trayectoria del chorro.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 12.2', 'Chorro por Orificio y Derrame Libre', 'Chorro por Orificio y Derrame Libre', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para analizar la salida de caudal por orificios, el coeficiente de descarga y la trayectoria del chorro.', 'Equipo para analizar la salida de caudal por orificios, el coeficiente de descarga y la trayectoria del chorro.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 13.1', 'Calibración de Manómetros', 'Calibración de Manómetros', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para realizar prácticas de calibración de manómetros y comprobación de lecturas de presión.', 'Equipo para realizar prácticas de calibración de manómetros y comprobación de lecturas de presión.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 14.1', 'Determinación de Viscosidades y Coeficientes de Resistencia', 'Determinación de Viscosidades y Coeficientes de Resistencia', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para determinar la viscosidad de fluidos y analizar coeficientes de resistencia mediante ensayos didácticos.', 'Equipo para determinar la viscosidad de fluidos y analizar coeficientes de resistencia mediante ensayos didácticos.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 14.2', 'Número de Reynolds', 'Número de Reynolds', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para visualizar regímenes de flujo laminar, transicional y turbulento y determinar el número de Reynolds.', 'Equipo para visualizar regímenes de flujo laminar, transicional y turbulento y determinar el número de Reynolds.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 14.3', 'Viscosidad POR Caída DE Bola', 'Viscosidad POR Caída DE Bola', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para determinar la viscosidad de fluidos y analizar coeficientes de resistencia mediante ensayos didácticos.', 'Equipo para determinar la viscosidad de fluidos y analizar coeficientes de resistencia mediante ensayos didácticos.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 15.1', 'Vórtice Forzado', 'Vórtice Forzado', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar la formación y características de vórtices libres y forzados en fluidos.', 'Equipo para estudiar la formación y características de vórtices libres y forzados en fluidos.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 15.2', 'Torbellinos Libres y Forzados', 'Torbellinos Libres y Forzados', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar la formación y características de vórtices libres y forzados en fluidos.', 'Equipo para estudiar la formación y características de vórtices libres y forzados en fluidos.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 17.1', 'Fricción en Tuberías', 'Fricción en Tuberías', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para analizar pérdidas de energía por fricción en tuberías y relacionarlas con el régimen de flujo.', 'Equipo para analizar pérdidas de energía por fricción en tuberías y relacionarlas con el régimen de flujo.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 17.2', 'Pérdidas de Energía en Tubos', 'Pérdidas de Energía en Tubos', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para medir y analizar pérdidas de carga o pérdidas de energía en tuberías, accesorios y acodamientos.', 'Equipo para medir y analizar pérdidas de carga o pérdidas de energía en tuberías, accesorios y acodamientos.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 18.1', 'Pérdidas de Carga Secundaria', 'Pérdidas de Carga Secundaria', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para medir y analizar pérdidas de carga o pérdidas de energía en tuberías, accesorios y acodamientos.', 'Equipo para medir y analizar pérdidas de carga o pérdidas de energía en tuberías, accesorios y acodamientos.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 18.2', 'Pérdidas de Energía en Acodamientos', 'Pérdidas de Energía en Acodamientos', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para medir y analizar pérdidas de carga o pérdidas de energía en tuberías, accesorios y acodamientos.', 'Equipo para medir y analizar pérdidas de carga o pérdidas de energía en tuberías, accesorios y acodamientos.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 23.1', 'Estudio de los Medidores de Caudal', 'Estudio de los Medidores de Caudal', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar, comparar y demostrar distintos sistemas de medición de caudal.', 'Equipo para estudiar, comparar y demostrar distintos sistemas de medición de caudal.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 27.2', 'Redes de Flujo y Fricción en Tuberías', 'Redes de Flujo y Fricción en Tuberías', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para analizar pérdidas de energía por fricción en tuberías y relacionarlas con el régimen de flujo.', 'Equipo para analizar pérdidas de energía por fricción en tuberías y relacionarlas con el régimen de flujo.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 28.1', 'Aparato de Pascal', 'Aparato de Pascal', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para demostrar el principio de Pascal y su aplicación en la transmisión de presión en fluidos.', 'Equipo para demostrar el principio de Pascal y su aplicación en la transmisión de presión en fluidos.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 29.1', 'Estática de Fluidos y Manometría', 'Estática de Fluidos y Manometría', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar la medición de presión mediante manómetros y comparar distintos sistemas de lectura.', 'Equipo para estudiar la medición de presión mediante manómetros y comparar distintos sistemas de lectura.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 29.3', 'Estudio y Comparación de Manómetros', 'Estudio y Comparación de Manómetros', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar la medición de presión mediante manómetros y comparar distintos sistemas de lectura.', 'Equipo para estudiar la medición de presión mediante manómetros y comparar distintos sistemas de lectura.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 30.1', 'Propiedades de los Fluidos', 'Propiedades de los Fluidos', NULL, 'FL - Mecánica de fluidos', 'FL', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Conjunto didáctico para analizar propiedades físicas de los fluidos mediante prácticas de laboratorio.', 'Conjunto didáctico para analizar propiedades físicas de los fluidos mediante prácticas de laboratorio.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FLB 03.1', 'Módulo – Bombas Serie-paralelo', 'Módulo – Bombas Serie-paralelo', NULL, 'FLB - Módulos para banco hidráulico', 'FLB', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FLB 03.2', 'Módulo – Características de la Bomba Centrífuga', 'Módulo – Características de la Bomba Centrífuga', NULL, 'FLB - Módulos para banco hidráulico', 'FLB', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FLB 06.2', 'Teorema de Bernoulli', 'Teorema de Bernoulli', NULL, 'FLB - Módulos para banco hidráulico', 'FLB', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo didáctico de fundamentos de mecánica de fluidos para prácticas de laboratorio relacionadas con teorema de bernoulli.', 'Equipo didáctico de fundamentos de mecánica de fluidos para prácticas de laboratorio relacionadas con teorema de bernoulli.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FLB 10.1', 'Presión Hidrostática', 'Presión Hidrostática', NULL, 'FLB - Módulos para banco hidráulico', 'FLB', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo didáctico de fundamentos de mecánica de fluidos para prácticas de laboratorio relacionadas con presión hidrostática.', 'Equipo didáctico de fundamentos de mecánica de fluidos para prácticas de laboratorio relacionadas con presión hidrostática.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FLB 11.1', 'Impacto de Chorro', 'Impacto de Chorro', NULL, 'FLB - Módulos para banco hidráulico', 'FLB', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar la fuerza ejercida por un chorro de agua sobre distintos álabes o superficies de impacto.', 'Equipo para estudiar la fuerza ejercida por un chorro de agua sobre distintos álabes o superficies de impacto.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FLB 13.1', 'Calibrador de Peso Muerto', 'Calibrador de Peso Muerto', NULL, 'FLB - Módulos para banco hidráulico', 'FLB', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para calibrar un manómetro Bourdon mediante un calibrador de peso muerto y evaluar su precisión de lectura.', 'Equipo para calibrar un manómetro Bourdon mediante un calibrador de peso muerto y evaluar su precisión de lectura.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FLB 14.2', 'Demostración de Osborne Reynolds', 'Demostración de Osborne Reynolds', NULL, 'FLB - Módulos para banco hidráulico', 'FLB', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para visualizar regímenes de flujo laminar, transicional y turbulento y determinar el número de Reynolds.', 'Equipo para visualizar regímenes de flujo laminar, transicional y turbulento y determinar el número de Reynolds.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FLB 23.1', 'Demostración de Caudalímetros', 'Demostración de Caudalímetros', NULL, 'FLB - Módulos para banco hidráulico', 'FLB', 'A - Fundamentos de Mecánica de Fluidos', 'A', 'Equipo para estudiar, comparar y demostrar distintos sistemas de medición de caudal.', 'Equipo para estudiar, comparar y demostrar distintos sistemas de medición de caudal.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 03.1', 'Bombas Serie-paralelo', 'Bombas Serie-paralelo', NULL, 'FL - Mecánica de fluidos', 'FL', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 03.1i', 'Bombas Serie Paralelo Informatizado (incluye Ordenador)', 'Bombas Serie Paralelo Informatizado (incluye Ordenador)', NULL, 'FL - Mecánica de fluidos', 'FL', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 03.2', 'Características DE LAS Bombas Centrífugas', 'Características DE LAS Bombas Centrífugas', NULL, 'FL - Mecánica de fluidos', 'FL', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 07.1', 'Ventilador Axial', 'Ventilador Axial', NULL, 'FL - Mecánica de fluidos', 'FL', 'B - Máquinas y Turbomáquinas Hidráulicas | D - Aerodinámica', 'B, D', 'Equipo para estudiar el funcionamiento y las curvas características de un ventilador axial.', 'Equipo para estudiar el funcionamiento y las curvas características de un ventilador axial.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 07.2', 'Ventilador Centrífugo', 'Ventilador Centrífugo', NULL, 'FL - Mecánica de fluidos', 'FL', 'B - Máquinas y Turbomáquinas Hidráulicas | D - Aerodinámica', 'B, D', 'Equipo para estudiar el funcionamiento y las curvas características de un ventilador centrífugo.', 'Equipo para estudiar el funcionamiento y las curvas características de un ventilador centrífugo.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MH 01.1', 'Unidad DE Demostración DE Bomba Centrífuga', 'Unidad DE Demostración DE Bomba Centrífuga', NULL, 'MH - Máquinas hidráulicas', 'MH', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TH 01.1', 'Turbina Pelton – Freno Fricción', 'Turbina Pelton – Freno Fricción', NULL, 'TH - Turbomáquinas hidráulicas', 'TH', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo para analizar pérdidas de energía por fricción en tuberías y relacionarlas con el régimen de flujo.', 'Equipo para analizar pérdidas de energía por fricción en tuberías y relacionarlas con el régimen de flujo.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TH 01.2', 'Turbina Francis – Freno Fricción', 'Turbina Francis – Freno Fricción', NULL, 'TH - Turbomáquinas hidráulicas', 'TH', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo para analizar pérdidas de energía por fricción en tuberías y relacionarlas con el régimen de flujo.', 'Equipo para analizar pérdidas de energía por fricción en tuberías y relacionarlas con el régimen de flujo.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TH 01.4', 'Turbina Kaplan/hélice – Freno Fricción', 'Turbina Kaplan/hélice – Freno Fricción', NULL, 'TH - Turbomáquinas hidráulicas', 'TH', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo para analizar pérdidas de energía por fricción en tuberías y relacionarlas con el régimen de flujo.', 'Equipo para analizar pérdidas de energía por fricción en tuberías y relacionarlas con el régimen de flujo.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TH 03.1', 'Turbina Pelton – Freno Eléctrico', 'Turbina Pelton – Freno Eléctrico', NULL, 'TH - Turbomáquinas hidráulicas', 'TH', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TH 03.2', 'Turbina Francis – Freno Eléctrico', 'Turbina Francis – Freno Eléctrico', NULL, 'TH - Turbomáquinas hidráulicas', 'TH', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TH 03.4', 'Turbina Kaplan/hélice – Freno Eléctrico', 'Turbina Kaplan/hélice – Freno Eléctrico', NULL, 'TH - Turbomáquinas hidráulicas', 'TH', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TH 04.1', 'Turbina Pelton Autónoma – Freno Eléctrico Computerizada', 'Turbina Pelton Autónoma – Freno Eléctrico Computerizada', NULL, 'TH - Turbomáquinas hidráulicas', 'TH', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TH 04.2', 'Turbina Francis Autónoma – Freno Eléctrico Computerizada', 'Turbina Francis Autónoma – Freno Eléctrico Computerizada', NULL, 'TH - Turbomáquinas hidráulicas', 'TH', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TH 04.4', 'Turbina Kaplan/hélice Autónoma – Freno Eléctrico Computerizada', 'Turbina Kaplan/hélice Autónoma – Freno Eléctrico Computerizada', NULL, 'TH - Turbomáquinas hidráulicas', 'TH', 'B - Máquinas y Turbomáquinas Hidráulicas', 'B', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 05.1', 'Canal Hidrodinámico 2,5m', 'Canal Hidrodinámico 2,5m', NULL, 'FL - Mecánica de fluidos', 'FL', 'C - Hidráulica, Hidrología y Tratamiento de aguas', 'C', 'Canal de ensayos para estudiar el comportamiento de fluidos en canales abiertos y realizar prácticas de hidráulica.', 'Canal de ensayos para estudiar el comportamiento de fluidos en canales abiertos y realizar prácticas de hidráulica.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 05.3', 'Canal Hidrodinámico 5m', 'Canal Hidrodinámico 5m', NULL, 'FL - Mecánica de fluidos', 'FL', 'C - Hidráulica, Hidrología y Tratamiento de aguas', 'C', 'Canal de ensayos para estudiar el comportamiento de fluidos en canales abiertos y realizar prácticas de hidráulica.', 'Canal de ensayos para estudiar el comportamiento de fluidos en canales abiertos y realizar prácticas de hidráulica.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 05.4', 'Canal Hidrodinámico 5m para Banco', 'Canal Hidrodinámico 5m para Banco', NULL, 'FL - Mecánica de fluidos', 'FL', 'C - Hidráulica, Hidrología y Tratamiento de aguas', 'C', 'Canal de ensayos para estudiar el comportamiento de fluidos en canales abiertos y realizar prácticas de hidráulica.', 'Canal de ensayos para estudiar el comportamiento de fluidos en canales abiertos y realizar prácticas de hidráulica.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 05.5', 'Canal Hidrodinámico para Banco Hidráulico 2,5m', 'Canal Hidrodinámico para Banco Hidráulico 2,5m', NULL, 'FL - Mecánica de fluidos', 'FL', 'C - Hidráulica, Hidrología y Tratamiento de aguas', 'C', 'Canal de ensayos para estudiar el comportamiento de fluidos en canales abiertos y realizar prácticas de hidráulica.', 'Canal de ensayos para estudiar el comportamiento de fluidos en canales abiertos y realizar prácticas de hidráulica.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 09.1', 'Golpe de Ariete', 'Golpe de Ariete', NULL, 'FL - Mecánica de fluidos', 'FL', 'C - Hidráulica, Hidrología y Tratamiento de aguas', 'C', 'Equipo para estudiar el fenómeno de ariete hidráulico o golpe de ariete y analizar variaciones bruscas de presión en conducciones.', 'Equipo para estudiar el fenómeno de ariete hidráulico o golpe de ariete y analizar variaciones bruscas de presión en conducciones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 16.1', 'Visualización de Flujo', 'Visualización de Flujo', NULL, 'FL - Mecánica de fluidos', 'FL', 'C - Hidráulica, Hidrología y Tratamiento de aguas', 'C', 'Equipo para observar y estudiar patrones de flujo, líneas de corriente y fenómenos hidráulicos de forma visual.', 'Equipo para observar y estudiar patrones de flujo, líneas de corriente y fenómenos hidráulicos de forma visual.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FL 16.2', 'Canal Miniatura de Visualización de Flujo', 'Canal Miniatura de Visualización de Flujo', NULL, 'FL - Mecánica de fluidos', 'FL', 'C - Hidráulica, Hidrología y Tratamiento de aguas', 'C', 'Equipo para observar y estudiar patrones de flujo, líneas de corriente y fenómenos hidráulicos de forma visual.', 'Equipo para observar y estudiar patrones de flujo, líneas de corriente y fenómenos hidráulicos de forma visual.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('FLB 09.2', 'Estudio del Fenómeno de Ariete Hidráulico', 'Estudio del Fenómeno de Ariete Hidráulico', NULL, 'FLB - Módulos para banco hidráulico', 'FLB', 'C - Hidráulica, Hidrología y Tratamiento de aguas', 'C', 'Equipo para estudiar el fenómeno de ariete hidráulico o golpe de ariete y analizar variaciones bruscas de presión en conducciones.', 'Equipo para estudiar el fenómeno de ariete hidráulico o golpe de ariete y analizar variaciones bruscas de presión en conducciones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('HD 06.1', 'Canal de Demostración de Flujo Hidráulico', 'Canal de Demostración de Flujo Hidráulico', NULL, 'HD - Hidráulica e hidrología', 'HD', 'C - Hidráulica, Hidrología y Tratamiento de aguas', 'C', 'Canal transparente de demostración para estudiar el comportamiento del flujo hidráulico en canales abiertos y conductos cerrados.', 'Canal transparente de demostración para estudiar el comportamiento del flujo hidráulico en canales abiertos y conductos cerrados.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('HD 10.1', 'Lisímetro de Demostración', 'Lisímetro de Demostración', NULL, 'HD - Hidráulica e hidrología', 'HD', 'C - Hidráulica, Hidrología y Tratamiento de aguas', 'C', 'Demostrador para estudiar infiltración, drenaje y balance hídrico en suelos mediante un montaje de laboratorio.', 'Demostrador para estudiar infiltración, drenaje y balance hídrico en suelos mediante un montaje de laboratorio.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('HD 11.1', 'Demostrador de Infiltración', 'Demostrador de Infiltración', NULL, 'HD - Hidráulica e hidrología', 'HD', 'C - Hidráulica, Hidrología y Tratamiento de aguas', 'C', 'Equipo para demostrar procesos de infiltración y analizar el movimiento del agua a través de medios porosos.', 'Equipo para demostrar procesos de infiltración y analizar el movimiento del agua a través de medios porosos.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TA 02.2', 'Tanque de Sedimentación', 'Tanque de Sedimentación', NULL, 'TA - Tratamiento de aguas', 'TA', 'C - Hidráulica, Hidrología y Tratamiento de aguas | I - Ingeniería Química', 'C, I', 'Equipo para estudiar la separación de partículas por sedimentación y visualizar el comportamiento de suspensiones.', 'Equipo para estudiar la separación de partículas por sedimentación y visualizar el comportamiento de suspensiones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TA 03.2', 'Ensayo de Sedimentación', 'Ensayo de Sedimentación', NULL, 'TA - Tratamiento de aguas', 'TA', 'C - Hidráulica, Hidrología y Tratamiento de aguas | I - Ingeniería Química', 'C, I', 'Equipo para estudiar y visualizar el fenómeno de sedimentación y comparar el comportamiento de suspensiones con distintas características.', 'Equipo para estudiar y visualizar el fenómeno de sedimentación y comparar el comportamiento de suspensiones con distintas características.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('EN 01.4', 'Demostrador de Energía Fotovoltaica Aislada', 'Demostrador de Energía Fotovoltaica Aislada', NULL, 'EN - Energías renovables', 'EN', 'E - Energías Renovables', 'E', 'Equipo didáctico para estudiar instalaciones solares fotovoltaicas, sus componentes y modos de funcionamiento.', 'Equipo didáctico para estudiar instalaciones solares fotovoltaicas, sus componentes y modos de funcionamiento.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('EN 01.4PC', 'Demostrador de Energía Fotovoltaica Aislada con PC', 'Demostrador de Energía Fotovoltaica Aislada con PC', NULL, 'EN - Energías renovables', 'EN', 'E - Energías Renovables', 'E', 'Equipo didáctico para estudiar instalaciones solares fotovoltaicas, sus componentes y modos de funcionamiento.', 'Equipo didáctico para estudiar instalaciones solares fotovoltaicas, sus componentes y modos de funcionamiento.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('EN 01.5', 'Demostrador de Energía Fotovoltaica Aislada y Red', 'Demostrador de Energía Fotovoltaica Aislada y Red', NULL, 'EN - Energías renovables', 'EN', 'E - Energías Renovables', 'E', 'Equipo didáctico para estudiar instalaciones solares fotovoltaicas, sus componentes y modos de funcionamiento.', 'Equipo didáctico para estudiar instalaciones solares fotovoltaicas, sus componentes y modos de funcionamiento.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('EN 01.6', 'Entrenador de Energía Fotovoltaica con PC', 'Entrenador de Energía Fotovoltaica con PC', NULL, 'EN - Energías renovables', 'EN', 'E - Energías Renovables', 'E', 'Equipo didáctico para estudiar instalaciones solares fotovoltaicas, sus componentes y modos de funcionamiento.', 'Equipo didáctico para estudiar instalaciones solares fotovoltaicas, sus componentes y modos de funcionamiento.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('EN 01.7', 'Entrenador DE Fotovoltaica A RED', 'Entrenador DE Fotovoltaica A RED', NULL, 'EN - Energías renovables', 'EN', 'E - Energías Renovables', 'E', 'Equipo didáctico para estudiar instalaciones solares fotovoltaicas, sus componentes y modos de funcionamiento.', 'Equipo didáctico para estudiar instalaciones solares fotovoltaicas, sus componentes y modos de funcionamiento.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('EN 04.1', 'Banco de Ensayo de Aerogeneradores', 'Banco de Ensayo de Aerogeneradores', NULL, 'EN - Energías renovables', 'EN', 'E - Energías Renovables', 'E', 'Equipo didáctico para estudiar generación eólica, aerogeneradores y sistemas de conexión aislada o a red.', 'Equipo didáctico para estudiar generación eólica, aerogeneradores y sistemas de conexión aislada o a red.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('EN 04.2', 'Entrenador Planta de Energía Eólica', 'Entrenador Planta de Energía Eólica', NULL, 'EN - Energías renovables', 'EN', 'E - Energías Renovables', 'E', 'Equipo didáctico para estudiar generación eólica, aerogeneradores y sistemas de conexión aislada o a red.', 'Equipo didáctico para estudiar generación eólica, aerogeneradores y sistemas de conexión aislada o a red.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('EN 04.3', 'Entrenador de Micogeneración Eólica con Conexión a Red', 'Entrenador de Micogeneración Eólica con Conexión a Red', NULL, 'EN - Energías renovables', 'EN', 'E - Energías Renovables', 'E', 'Equipo didáctico para estudiar generación eólica, aerogeneradores y sistemas de conexión aislada o a red.', 'Equipo didáctico para estudiar generación eólica, aerogeneradores y sistemas de conexión aislada o a red.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('EN 04.4', 'Entrenador Planta de Energía Eólica Aislada', 'Entrenador Planta de Energía Eólica Aislada', NULL, 'EN - Energías renovables', 'EN', 'E - Energías Renovables', 'E', 'Equipo didáctico para estudiar generación eólica, aerogeneradores y sistemas de conexión aislada o a red.', 'Equipo didáctico para estudiar generación eólica, aerogeneradores y sistemas de conexión aislada o a red.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('EN 04.5', 'Entrenador de Energía Eólica Aislada y Red', 'Entrenador de Energía Eólica Aislada y Red', NULL, 'EN - Energías renovables', 'EN', 'E - Energías Renovables', 'E', 'Equipo didáctico para estudiar generación eólica, aerogeneradores y sistemas de conexión aislada o a red.', 'Equipo didáctico para estudiar generación eólica, aerogeneradores y sistemas de conexión aislada o a red.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('EN 05.1', 'Planta Hidroeléctrica con Turbina Pelton', 'Planta Hidroeléctrica con Turbina Pelton', NULL, 'EN - Energías renovables', 'EN', 'E - Energías Renovables', 'E', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', 'Equipo para ensayar turbinas hidráulicas y analizar su comportamiento, rendimiento y curvas características.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('AC 03.1', 'Demostración de Bomba de Calor', 'Demostración de Bomba de Calor', NULL, 'AC - Aire acondicionado / bomba de calor', 'AC', 'F - Termodinámica', 'F', 'Equipo para demostrar el funcionamiento de una bomba de calor y analizar sus variables termodinámicas.', 'Equipo para demostrar el funcionamiento de una bomba de calor y analizar sus variables termodinámicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('IT 03.2', 'Transferencia de Calor por Convección Natural y Forzada', 'Transferencia de Calor por Convección Natural y Forzada', NULL, 'IT - Intercambio térmico', 'IT', 'F - Termodinámica', 'F', 'Equipo para estudiar transferencia de calor por convección natural y forzada mediante prácticas de laboratorio.', 'Equipo para estudiar transferencia de calor por convección natural y forzada mediante prácticas de laboratorio.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('RF 01.1', 'Cámara Frigorífica', 'Cámara Frigorífica', NULL, 'RF - Refrigeración', 'RF', 'F - Termodinámica', 'F', 'Equipo para estudiar el funcionamiento de una cámara frigorífica y los principios de refrigeración aplicada.', 'Equipo para estudiar el funcionamiento de una cámara frigorífica y los principios de refrigeración aplicada.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 01.1', 'Alimentador para Intercambiadores de Calor', 'Alimentador para Intercambiadores de Calor', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 01.2', 'Intercambiador de Calor de Placas', 'Intercambiador de Calor de Placas', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 01.3', 'Intercambiador de Calor por Haz de Tubos', 'Intercambiador de Calor por Haz de Tubos', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 01.4', 'Intercambiador de Calor de Tubos Concéntricos', 'Intercambiador de Calor de Tubos Concéntricos', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 01.5', 'Intercambiador de Calor de Doble Camisa y Serpentín', 'Intercambiador de Calor de Doble Camisa y Serpentín', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 02.1', 'Torre de Enfriamiento de Agua', 'Torre de Enfriamiento de Agua', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 02.2', 'Torre de Enfriamiento Tipo A', 'Torre de Enfriamiento Tipo A', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 02.3', 'Torre de Enfriamiento Tipo B', 'Torre de Enfriamiento Tipo B', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 02.4', 'Torre de Enfriamiento Tipo C', 'Torre de Enfriamiento Tipo C', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 02.5', 'Torre de Enfriamiento Tipo D', 'Torre de Enfriamiento Tipo D', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 02.6', 'Torre de Enfriamiento Tipo E', 'Torre de Enfriamiento Tipo E', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', 'Equipo para estudiar el funcionamiento de torres de enfriamiento de agua y los procesos de transferencia de calor y masa.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 06.1', 'Conducción de Calor en Líquidos y Gases', 'Conducción de Calor en Líquidos y Gases', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar la conducción de calor en líquidos y gases y analizar gradientes térmicos.', 'Equipo para estudiar la conducción de calor en líquidos y gases y analizar gradientes térmicos.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TC 07.1', 'Entrenador de Intercambiadores de Calor Tubulares', 'Entrenador de Intercambiadores de Calor Tubulares', NULL, 'TC - Transferencia de calor', 'TC', 'F - Termodinámica', 'F', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', 'Equipo para estudiar el intercambio de calor y comparar el comportamiento térmico de diferentes configuraciones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TD 01.1', 'Banco de Ensayo de Motores de Combustión Interna', 'Banco de Ensayo de Motores de Combustión Interna', NULL, 'TD - Termodinámica / motores', 'TD', 'F - Termodinámica', 'F', 'Banco de ensayo para estudiar motores, variables de funcionamiento y rendimiento en aplicaciones termodinámicas.', 'Banco de ensayo para estudiar motores, variables de funcionamiento y rendimiento en aplicaciones termodinámicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('TD 01.2', 'Banco de Ensayo de Motores', 'Banco de Ensayo de Motores', NULL, 'TD - Termodinámica / motores', 'TD', 'F - Termodinámica', 'F', 'Banco de ensayo para estudiar motores, variables de funcionamiento y rendimiento en aplicaciones termodinámicas.', 'Banco de ensayo para estudiar motores, variables de funcionamiento y rendimiento en aplicaciones termodinámicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('IQ 01.5', 'Secado por Convección', 'Secado por Convección', NULL, 'IQ - Ingeniería química', 'IQ', 'I - Ingeniería Química', 'I', 'Equipo para estudiar transferencia de calor por convección natural y forzada mediante prácticas de laboratorio.', 'Equipo para estudiar transferencia de calor por convección natural y forzada mediante prácticas de laboratorio.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('IQ 02.1', 'Separación por Centrifugación', 'Separación por Centrifugación', NULL, 'IQ - Ingeniería química', 'IQ', 'I - Ingeniería Química', 'I', 'Equipo para estudiar la separación de mezclas mediante centrifugación y evaluar la eficiencia del proceso.', 'Equipo para estudiar la separación de mezclas mediante centrifugación y evaluar la eficiencia del proceso.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('ST 01.1', 'Bastidor para Estructuras Planas', 'Bastidor para Estructuras Planas', NULL, 'ST - Estructuras', 'ST', 'K - Mecánica', 'K', 'Bastidor didáctico para montar y estudiar estructuras planas en prácticas de mecánica estructural.', 'Bastidor didáctico para montar y estudiar estructuras planas en prácticas de mecánica estructural.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('ST 01.2', 'Estudio de Pórticos', 'Estudio de Pórticos', NULL, 'ST - Estructuras', 'ST', 'K - Mecánica', 'K', 'Equipo para estudiar el comportamiento de pórticos sometidos a cargas y analizar deformaciones estructurales.', 'Equipo para estudiar el comportamiento de pórticos sometidos a cargas y analizar deformaciones estructurales.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('ST 03.1', 'Vigas Continuas', 'Vigas Continuas', NULL, 'ST - Estructuras', 'ST', 'K - Mecánica', 'K', 'Equipo para estudiar vigas continuas, apoyos, cargas y distribución de esfuerzos y deformaciones.', 'Equipo para estudiar vigas continuas, apoyos, cargas y distribución de esfuerzos y deformaciones.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('ST.Z.01', 'Sistema de Pesas Serie ST', 'Sistema de Pesas Serie ST', NULL, 'STZ - STZ', 'STZ', 'K - Mecánica', 'K', 'Sistema de pesas para aplicar cargas controladas en equipos de la serie ST.', 'Sistema de pesas para aplicar cargas controladas en equipos de la serie ST.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('ST.Z.02', 'Sistema de Medición de Desplazamientos Serie ST', 'Sistema de Medición de Desplazamientos Serie ST', NULL, 'STZ - STZ', 'STZ', 'K - Mecánica', 'K', 'Sistema de medición de desplazamientos para registrar deformaciones en ensayos de estructuras de la serie ST.', 'Sistema de medición de desplazamientos para registrar deformaciones en ensayos de estructuras de la serie ST.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MM01', 'Kit de Montaje: Grifo de Bola y Válvula de Cierre', 'Kit de Montaje: Grifo de Bola y Válvula de Cierre', NULL, 'MM - Mantenimiento y montaje', 'MM', 'N - Mantenimiento', 'N', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MM02', 'Kit de Montaje: Compresor de Émbolo', 'Kit de Montaje: Compresor de Émbolo', NULL, 'MM - Mantenimiento y montaje', 'MM', 'N - Mantenimiento', 'N', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MM03', 'Montaje y Mantenimiento: Bomba Centrífuga Multietapa', 'Montaje y Mantenimiento: Bomba Centrífuga Multietapa', NULL, 'MM - Mantenimiento y montaje', 'MM', 'N - Mantenimiento', 'N', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MM04', 'Montaje y Mantenimiento: Bomba de Tornillo', 'Montaje y Mantenimiento: Bomba de Tornillo', NULL, 'MM - Mantenimiento y montaje', 'MM', 'N - Mantenimiento', 'N', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MM05', 'Montaje y Mantenimiento: Bomba de Diafragma', 'Montaje y Mantenimiento: Bomba de Diafragma', NULL, 'MM - Mantenimiento y montaje', 'MM', 'N - Mantenimiento', 'N', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MM06', 'Montaje y Mantenimiento: Bomba de Émbolo', 'Montaje y Mantenimiento: Bomba de Émbolo', NULL, 'MM - Mantenimiento y montaje', 'MM', 'N - Mantenimiento', 'N', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MM07', 'Montaje y Mantenimiento: Bomba de Engranajes', 'Montaje y Mantenimiento: Bomba de Engranajes', NULL, 'MM - Mantenimiento y montaje', 'MM', 'N - Mantenimiento', 'N', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', 'Equipo o módulo para estudiar el funcionamiento, características y comportamiento de bombas hidráulicas.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MM08', 'Kit de Montaje: Cojinete de Deslizamiento Hidrodinámico', 'Kit de Montaje: Cojinete de Deslizamiento Hidrodinámico', NULL, 'MM - Mantenimiento y montaje', 'MM', 'N - Mantenimiento', 'N', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MM09', 'Kit de Montaje: Válvula de Cierre', 'Kit de Montaje: Válvula de Cierre', NULL, 'MM - Mantenimiento y montaje', 'MM', 'N - Mantenimiento', 'N', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MM10', 'Kit de Montaje: Engranaje Combinado', 'Kit de Montaje: Engranaje Combinado', NULL, 'MM - Mantenimiento y montaje', 'MM', 'N - Mantenimiento', 'N', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP)),
  ('MM11', 'Kit Compuerta Plana de Cuña y Válvula de Asiento Inclinado', 'Kit Compuerta Plana de Cuña y Válvula de Asiento Inclinado', NULL, 'MM - Mantenimiento y montaje', 'MM', 'N - Mantenimiento', 'N', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', 'Kit didáctico para prácticas de montaje, desmontaje, identificación de componentes y mantenimiento del conjunto mecánico.', NULL, TRUE, COALESCE(NOW(), CURRENT_TIMESTAMP), COALESCE(NOW(), CURRENT_TIMESTAMP))
ON DUPLICATE KEY UPDATE name = VALUES(name), name_es = VALUES(name_es), family = VALUES(family), family_code = VALUES(family_code), category = VALUES(category), category_codes = VALUES(category_codes), description = VALUES(description), description_es = VALUES(description_es), active = TRUE, updated_at = COALESCE(NOW(), CURRENT_TIMESTAMP);

UPDATE products p JOIN product_families f ON f.code = p.family_code SET p.family_id = f.id WHERE p.family_code IS NOT NULL;

DELETE pca FROM product_category_assignments pca JOIN products p ON p.id = pca.product_id WHERE p.code IN ('FL 01.1', 'FL 01.2', 'FL 01.3', 'FL 01.4', 'FL 01.6', 'FL 01.7', 'FL 02.1', 'FL 04.1', 'FL 06.1', 'FL 06.2', 'FL 06.3', 'FL 09.2', 'FL 10.1', 'FL 10.2', 'FL 11.1', 'FL 12.1', 'FL 12.2', 'FL 13.1', 'FL 14.1', 'FL 14.2', 'FL 14.3', 'FL 15.1', 'FL 15.2', 'FL 17.1', 'FL 17.2', 'FL 18.1', 'FL 18.2', 'FL 23.1', 'FL 27.2', 'FL 28.1', 'FL 29.1', 'FL 29.3', 'FL 30.1', 'FLB 03.1', 'FLB 03.2', 'FLB 06.2', 'FLB 10.1', 'FLB 11.1', 'FLB 13.1', 'FLB 14.2', 'FLB 23.1', 'FL 03.1', 'FL 03.1i', 'FL 03.2', 'FL 07.1', 'FL 07.2', 'MH 01.1', 'TH 01.1', 'TH 01.2', 'TH 01.4', 'TH 03.1', 'TH 03.2', 'TH 03.4', 'TH 04.1', 'TH 04.2', 'TH 04.4', 'FL 05.1', 'FL 05.3', 'FL 05.4', 'FL 05.5', 'FL 09.1', 'FL 16.1', 'FL 16.2', 'FLB 09.2', 'HD 06.1', 'HD 10.1', 'HD 11.1', 'TA 02.2', 'TA 03.2', 'EN 01.4', 'EN 01.4PC', 'EN 01.5', 'EN 01.6', 'EN 01.7', 'EN 04.1', 'EN 04.2', 'EN 04.3', 'EN 04.4', 'EN 04.5', 'EN 05.1', 'AC 03.1', 'IT 03.2', 'RF 01.1', 'TC 01.1', 'TC 01.2', 'TC 01.3', 'TC 01.4', 'TC 01.5', 'TC 02.1', 'TC 02.2', 'TC 02.3', 'TC 02.4', 'TC 02.5', 'TC 02.6', 'TC 06.1', 'TC 07.1', 'TD 01.1', 'TD 01.2', 'IQ 01.5', 'IQ 02.1', 'ST 01.1', 'ST 01.2', 'ST 03.1', 'ST.Z.01', 'ST.Z.02', 'MM01', 'MM02', 'MM03', 'MM04', 'MM05', 'MM06', 'MM07', 'MM08', 'MM09', 'MM10', 'MM11');
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 01.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 01.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 01.3';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 01.4';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 01.6';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 01.7';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 02.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 04.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 06.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 06.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 06.3';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 09.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'FL 09.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 10.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 10.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 11.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 12.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 12.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 13.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 14.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 14.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 14.3';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 15.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 15.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 17.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 17.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 18.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 18.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 23.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 27.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 28.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 29.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 29.3';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FL 30.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FLB 03.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FLB 03.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FLB 06.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FLB 10.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FLB 11.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FLB 13.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FLB 14.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'A' WHERE p.code = 'FLB 23.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'FL 03.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'FL 03.1i';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'FL 03.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'FL 07.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'D' WHERE p.code = 'FL 07.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'FL 07.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'D' WHERE p.code = 'FL 07.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'MH 01.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'TH 01.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'TH 01.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'TH 01.4';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'TH 03.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'TH 03.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'TH 03.4';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'TH 04.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'TH 04.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'B' WHERE p.code = 'TH 04.4';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'FL 05.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'FL 05.3';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'FL 05.4';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'FL 05.5';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'FL 09.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'FL 16.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'FL 16.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'FLB 09.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'HD 06.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'HD 10.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'HD 11.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'TA 02.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'I' WHERE p.code = 'TA 02.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'C' WHERE p.code = 'TA 03.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'I' WHERE p.code = 'TA 03.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'E' WHERE p.code = 'EN 01.4';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'E' WHERE p.code = 'EN 01.4PC';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'E' WHERE p.code = 'EN 01.5';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'E' WHERE p.code = 'EN 01.6';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'E' WHERE p.code = 'EN 01.7';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'E' WHERE p.code = 'EN 04.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'E' WHERE p.code = 'EN 04.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'E' WHERE p.code = 'EN 04.3';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'E' WHERE p.code = 'EN 04.4';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'E' WHERE p.code = 'EN 04.5';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'E' WHERE p.code = 'EN 05.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'AC 03.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'IT 03.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'RF 01.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 01.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 01.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 01.3';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 01.4';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 01.5';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 02.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 02.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 02.3';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 02.4';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 02.5';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 02.6';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 06.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TC 07.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TD 01.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'F' WHERE p.code = 'TD 01.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'I' WHERE p.code = 'IQ 01.5';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'I' WHERE p.code = 'IQ 02.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'K' WHERE p.code = 'ST 01.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'K' WHERE p.code = 'ST 01.2';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'K' WHERE p.code = 'ST 03.1';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'K' WHERE p.code = 'ST.Z.01';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'K' WHERE p.code = 'ST.Z.02';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'N' WHERE p.code = 'MM01';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'N' WHERE p.code = 'MM02';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'N' WHERE p.code = 'MM03';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'N' WHERE p.code = 'MM04';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'N' WHERE p.code = 'MM05';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'N' WHERE p.code = 'MM06';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'N' WHERE p.code = 'MM07';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'N' WHERE p.code = 'MM08';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'N' WHERE p.code = 'MM09';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'N' WHERE p.code = 'MM10';
INSERT IGNORE INTO product_category_assignments (product_id, category_id) SELECT p.id, c.id FROM products p JOIN product_categories c ON c.code = 'N' WHERE p.code = 'MM11';

-- Backfill compatible para productos existentes creados antes de esta migracion.
UPDATE products SET name_es = COALESCE(name_es, name), description_es = COALESCE(description_es, description) WHERE name_es IS NULL OR description_es IS NULL;
